// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UsingDirectiveFormatter.Commands
{
	using System;

	/// <summary>
	/// Helper class that exposes all GUIDs used across VS Package.
	/// </summary>
	internal sealed partial class PackageGuids
	{
		public const string guidFormatCommandPackageString = "a385812e-17cc-4ed0-a6d0-f0d8db1ff294";
		public static Guid guidFormatCommandPackage = new Guid(guidFormatCommandPackageString);

		public const string guidFormatCommandPackageCmdSetString = "2bb0aad7-e323-43dc-883c-cab65d5684c7";
		public static Guid guidFormatCommandPackageCmdSet = new Guid(guidFormatCommandPackageCmdSetString);

		public const string guidImagesString = "961d78f4-8a1c-4636-bd61-6caa5cb67a0a";
		public static Guid guidImages = new Guid(guidImagesString);
	}
	/// <summary>
	/// Helper class that encapsulates all CommandIDs uses across VS Package.
	/// </summary>
	internal sealed partial class PackageIds
	{
		public const int MyMenuGroup = 0x1020;
		public const int FormatCommandId = 0x0100;
		public const int bmpPic1 = 1;
		public const int bmpPic2 = 2;
		public const int bmpPicSearch = 3;
		public const int bmpPicX = 4;
		public const int bmpPicArrows = 5;
		public const int bmpPicStrikethrough = 6;
	}
}
