// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UsingDirectiveFormatter
{
    internal sealed partial class Vsix
    {
        public const string Id = "UsingDirectiveFormatterVS2022.Mohorko G.2c532cfa-59ef-4e4e-8b4c-11a39ffd91cf";
        public const string Name = "Using Directive Formatter VS2022";
        public const string Description = @"Formats using namespace directives in C# code. Allows you to specify (with regex) which namespaces to put where. This is super helpful when you want to order usings from the system to domain. It also supports automatic sorting on Save.";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Gregor Mohorko";
        public const string Tags = "formatting";
    }
}
